=== Applied-Research-Associates-Inc/dtcvc-testbed/dtcvc/lib/dtcvc-scoring/triage_scorer/schemas/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "competitor-report",
    "title": "Competitor Health Report",
    "description": "A report on scorable health metrics of a virtual casualty",
    "type": "object",
    "properties": {
        "casualty_id": {
            "type": "number",
            "minimum": 0,
            "multipleOf": 1
        },
        "team": {
            "type": "string"
        },
        "system": {
            "type": "string"
        },
        "location": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "minimum": -90,
                    "maximum": 90
                },
                "longitude": {
                    "type": "number",
                    "exclusiveMinimum": -180,
                    "maximum": 180
                },
                "time_ago": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "latitude",
                "longitude",
                "time_ago"
            ]
        },
        "severe_hemorrhage": {
            "type": "number",
            "minimum": 0,
            "maximum": 1,
            "multipleOf": 1
        },
        "respiratory_distress": {
            "type": "number",
            "minimum": 0,
            "maximum": 1,
            "multipleOf": 1
        },
        "hr": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "number",
                    "minimum": 0
                },
                "time_ago": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "value",
                "time_ago"
            ]
        },
        "rr": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "number",
                    "minimum": 0
                },
                "time_ago": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "value",
                "time_ago"
            ]
        },
        "temp": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "number",
                    "minimum": 0
                },
                "time_ago": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "value",
                "time_ago"
            ]
        },
        "trauma_head": {
            "type": "number",
            "minimum": 0,
            "maximum": 2,
            "multipleOf": 1
        },
        "trauma_torso": {
            "type": "number",
            "minimum": 0,
            "maximum": 2,
            "multipleOf": 1
        },
        "trauma_lower_ext": {
            "type": "number",
            "minimum": 0,
            "maximum": 3,
            "multipleOf": 1
        },
        "trauma_upper_ext": {
            "type": "number",
            "minimum": 0,
            "maximum": 3,
            "multipleOf": 1
        },
        "alertness_ocular": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 2,
                    "multipleOf": 1
                },
                "time_ago": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "value",
                "time_ago"
            ]
        },
        "alertness_verbal": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 3,
                    "multipleOf": 1
                },
                "time_ago": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "value",
                "time_ago"
            ]
        },
        "alertness_motor": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 3,
                    "multipleOf": 1
                },
                "time_ago": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "value",
                "time_ago"
            ]
        }
    },
    "required": [
        "casualty_id",
        "team",
        "system",
        "location"
    ],
    "additionalProperties": false,
    "minProperties": 7
}

=== Applied-Research-Associates-Inc/dtcvc-testbed/dtcvc/lib/dtcvc-scoring/test/data/competitor_reports/cr_002.json
{
    "casualty_id": 2,
    "team": "team-2",
    "system": "drone-2",
    "location": {
        "latitude": 48.926889,
        "longitude": 8.110252,
        "time_ago": 90.0
    },
    "severe_hemorrhage": 0,
    "respiratory_distress": 0,
    "hr": {
        "value": 74.0,
        "time_ago": 90.0
    },
    "rr": {
        "value": 14.0,
        "time_ago": 90.0
    },
    "temp": {
        "value": 36.6,
        "time_ago": 90.0
    },
    "trauma_head": 0,
    "trauma_torso": 0,
    "trauma_lower_ext": 1,
    "trauma_upper_ext": 0,
    "alertness_ocular": {
        "value": 0,
        "time_ago": 90.0
    },
    "alertness_verbal": {
        "value": 0,
        "time_ago": 90.0
    },
    "alertness_motor": {
        "value": 1,
        "time_ago": 90.0
    }
}

=== Applied-Research-Associates-Inc/dtcvc-testbed/dtcvc/lib/dtcvc-scoring/test/data/competitor_reports/report_update_full_points.json
{
    "casualty_id": 0,
    "team": "team-1",
    "system": "drone-1",
    "location": {
        "latitude": 48.926884,
        "longitude": 8.110344,
        "time_ago": 90.0
    },
    "hr": {
        "value": 91.0,
        "time_ago": 90.0
    },
    "rr": {
        "value": 13.0,
        "time_ago": 90.0
    },
    "alertness_ocular": {
        "value": 1,
        "time_ago": 135.0
    },
    "alertness_verbal": {
        "value": 1,
        "time_ago": 135.0
    },
    "alertness_motor": {
        "value": 1,
        "time_ago": 135.0
    }
}
